title: 清音为羽 # 站点标题
description: Ching Jyu's Homepage
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
        comments: # 留言页，请先修改这里，确保使用的是你自己的repo！参照<https://giscus.app/>
          append: |
            <div class="giscus">
              Loading comments...
            </div>
            <script src="https://giscus.app/client.js"
              data-repo="chingjyu/chingjyu.github.io"
              data-repo-id="R_kgDORSeYiw"
              data-category="General"
              data-category-id="DIC_kwDORSeYi84C2xHB"
              data-mapping="url"
              data-strict="0"
              data-reactions-enabled="1"
              data-emit-metadata="0"
              data-input-position="top"
              data-theme="preferred_color_scheme"
              data-lang="en"
              crossorigin="anonymous"
              async>
            </script>
        default:
          html_lang: zh # <https://www.w3school.com.cn/tags/html_ref_language_codes.asp>
          color-mode: auto # <https://primer.style/css/storybook/?path=/docs/support-theming--docs>
          light-theme: light
          dark-theme: dark
          menu:
            nav: # 导航部分的内容，你也可以自己增加对应的链接
              - title: '主页 / Homepage'
                href: /
              - title: '关于 / About'
                href: /about/
              - title: '友链 / Friends'
                href: /friends/
              - title: 'GitHub'
                href: https://github.com/chingjyu
              - title: 'Email'
                href: mailto:i@chingjyu.cyou
            footer: |
              <div>
                (C) 2024-2026 Ching Jyu
              </div>
            jekyll-toc: # <https://github.com/allejo/jekyll-toc>
              enable: false
              prepend: |
                <style>
                  #wrap-toc {
                    padding-left: 3em;
                  }
                </style>
            prepend:
              - |
                <form class="SelectMenu-filter">
                  <input
                    class="SelectMenu-input form-control"
                    type="text"
                    placeholder="Search"
                    aria-label="Filter"
                    id="wrap-search-input"
                  />
                  <ol class="px-5" id="wrap-search-result"></ol>
                  <script
                    src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js"
                    async="async"
                    onload='
                  SimpleJekyllSearch({
                    json: "/assets/simple-jekyll-search/search.json",
                    searchInput: document.getElementById("wrap-search-input"),
                    resultsContainer: document.getElementById("wrap-search-result"),
                    searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                    limit: 9
                  })'
                  ></script>
                </form>
          append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/2019/01/18/基于Jekyll搭建个人博客/>
            - | # 页面加载动画，可在 <https://css-loaders.com/> 挑选
              <style>
                .loader {
                  width: calc(6*30px);
                  height: 50px;
                  display: flex;
                  filter: drop-shadow(30px 25px 0 currentColor) drop-shadow(60px 0 0 currentColor) drop-shadow(120px 0 0 currentColor);
                  clip-path: inset(0 100% 0 0);
                  animation: l12 2s infinite steps(7);
                }
                .loader:before {
                  content: "";
                  width: 30px;
                  height: 25px;
                  --c:no-repeat radial-gradient(farthest-side,currentColor 92%,#0000);
                  background:
                    var(--c) left /70% 70%,
                    var(--c) right/20% 20%,
                    var(--c) top    0 right 15%/20% 20%,
                    var(--c) bottom 0 right 15%/20% 20%;
                }
                @keyframes l12 {
                  100% {clip-path: inset(0 -30px 0 0)}
                }
                #wrap-loader {
                  width: 100vw;
                  height: 100vh;
                  position: fixed;
                  top: 0;
                  left: 0;
                  z-index: 999;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                }
                :root {
                  --fgColor-default: Black;
                  --bgColor-default: White;
                }
                @media (prefers-color-scheme: dark) {
                  :root {
                    --fgColor-default: White;
                    --bgColor-default: Black;
                  }
                }
                .loader {
                  color: var(--fgColor-default);
                }
                #wrap-loader {
                  background-color: var(--bgColor-default);
                }
              </style>
              <script>
                document.addEventListener("DOMContentLoaded", (event) => {
                  let x = document.getElementById("wrap-loader");
                  x.classList.add("fast", "anim-fade-out");
                  setTimeout('document.getElementById("wrap-loader").remove()', 300);
              });
              </script>
            - | # 一些页面优化标签，看不懂可跳过
              <meta
                http-equiv="content-type"
                content="text/html; charset=utf-8"
              />
              <meta
                name="viewport"
                content="width=device-width,minimum-scale=1,initial-scale=1"
              />
              <link
                rel="alternate"
                href="/feed.xml"
                title="RSS"
                type="application/rss+xml"
              />
            - | # 来自primer/css的页面样式，不要改
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/@primer/css@22.1.0/dist/primer.min.css"
              />
            - | # 代码高亮，可在 <https://www.npmjs.com/package/pygments-rouge-css> 挑选
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/pygments-rouge-css@0.1.0/perldoc.min.css"
              />
            - | # 字体
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/@fontsource/monaspace-xenon@5.2.5/index.min.css"
              />
              <link
                rel='stylesheet'
                href='https://unpkg.com/@chinese-fonts/jyhpws@2.0.0/dist/%E6%9E%81%E5%BD%B1%E6%AF%81%E7%89%87%E6%96%87%E5%AE%8B/result.css'
              />
              <style>
                body, .markdown-body {
                  font-family: "Monaspace Xenon", "极影毁片文宋 Medium", var(--fontStack-monospace, monospace);
                  font-feature-settings: "calt" 1, "liga" 1;
                }
              </style>
            - | # 填满页面
              <style>
                #wrap-content {
                  min-height: 100vh;
                }
              </style>
        page:
          title: # 为每个页面自动生成一个 H1 title
            enable: true
          prepend:
            - | # 首行缩进2字符，图片相应调整
              <style>
                .markdown-body p {
                  text-indent: 2em;
                }
                .markdown-body img {
                  max-width: calc(100% - 4em);
                }
              </style>
            - |
              <style>
              .markdown-body .highlight pre,
              .markdown-body pre {
                  padding: 0;
                  background: none;
                }
              </style>
          plugin:
            - smart_include:
                enable: true
                key: $
              append:
                | # 对KaTeX过长公式渲染超出页面的修正，感谢[@AmachiInori](https://github.com/wu-kan/wu-kan.github.io/issues/13)
                <link
                  rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/katex@0.16.27/dist/katex.min.css"
                />
                <style>
                  .katex-display>.katex {
                    white-space: normal;
                  }
                </style>
                <script
                  src="https://cdn.jsdelivr.net/combine/npm/katex@0.16.27/dist/katex.min.js,npm/katex@0.16.27/dist/contrib/auto-render.min.js"
                  async="async"
                  onload='renderMathInElement(document.body, { delimiters: [{left: "$$", right: "$$", display: true}, { left: "$", right: "$", display: false }, {left: "\\(", right: "\\)", display: false}, {left: "\\[", right: "\\]", display: true}]})'
                ></script>
            - smart_include:
                enable: true
                key: language-vega-lite
              append: |
                <style>
                  pre code.language-vega-lite {
                    display: none;
                  }
                </style>
                <script
                  src="https://cdn.jsdelivr.net/combine/npm/vega@6.2.0,npm/vega-lite@6.4.1,npm/vega-embed@7.1.0"
                  async="async"
                  onload='
                    for(let x of document.getElementsByClassName("language-vega-lite"))
                      if(x.nodeName=="CODE")
                      {
                        let m = document.createElement("div");
                        x.parentNode.insertAdjacentElement("beforebegin", m);
                        vegaEmbed(m, JSON.parse(x.textContent));
                      }'
                ></script>
            - smart_include:
                enable: true
                key: language-mermaid
              append: |
                <style>
                  pre code.language-mermaid {
                    display: none;
                  }
                </style>
                <script
                  src="https://cdn.jsdelivr.net/npm/mermaid@11.12.2/dist/mermaid.min.js"
                  async="async"
                  defer="defer"
                  onload='
                    for(let x of document.getElementsByClassName("language-mermaid"))
                      if(x.nodeName=="CODE")
                      {
                        let m = document.createElement("div");
                        m.classList.add("mermaid");
                        m.textContent = x.textContent;
                        x.parentNode.insertAdjacentElement("beforebegin", m);
                      }'
                ></script>
        post:
          date: # 显示博文时间
            enable: true
            prepend: post on
          wordcount: # 统计全文字数
            enable: false
            prepend: about
            unit: words
          readtime: # 计算文章阅读时间
            enable: false
            prepend: require
            unit: min
            divided_by: 300 # 正常人的阅读速度大概每分钟三百个字
          copyright:
          related_posts:
            enable: false
        home: # 展示页的配置可跳过，详见<https://revealjs.com/>
          append_to_section_tag:
            - key: data-markdown
            - key: data-separator # 水平展示页分隔符
              value: <!-- .slide -->
            - key: data-separator-vertical # 垂直展示页分隔符
              value: <!-- .slide vertical=true -->
          prepend: |
            <link
              rel="stylesheet"
              href="https://cdn.jsdelivr.net/combine/npm/reveal.js@5.2.1/dist/reveal.min.css,npm/reveal.js@5.2.1/dist/theme/serif.min.css"
            />
            <style>
              .reveal {
                font-feature-settings: "calt" 1, "liga" 1;
                --r-code-font: "Monaspace Xenon", "极影毁片文宋 Medium", var(--fontStack-monospace, monospace);
                --r-main-font: var(--r-code-font);
                --r-heading-font: var(--r-main-font);
                --r-main-color: var(--fgColor-default, var(--color-fg-default));
                --r-heading-color: var(--r-main-color);
                --r-link-color: var(--fgColor-accent, var(--color-accent-fg));
                --r-background-color: var(--bgColor-default, var(--color-canvas-default));
              }
              .reveal .slides {
                text-align: left;
              }
            </style>
          append: |
            <script
              src="https://cdn.jsdelivr.net/combine/npm/reveal.js@5.2.1/dist/reveal.min.js,npm/reveal.js@5.2.1/plugin/markdown/markdown.min.js,npm/reveal.js@5.2.1/plugin/math/math.min.js"
              defer="defer"
              onload="
              let x = document.getElementById('wrap-content');
              x.classList.add('reveal');
              Reveal.initialize({
                scrollActivationWidth: null,
                height: '100%',
                mouseWheel: true,
                navigationMode: 'linear',
                plugins: [ RevealMarkdown,RevealMath.KaTeX ]
              });
            "></script>

compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: all # set to '[]' to but something wrong with syntax_highlighter_opts line_numbers true
  blanklines: false
  profile: false
  startings: []

# githubpage上支持的插件见<https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源
  - jekyll-redirect-from # 站点页面重定向
  - jekyll-paginate
  - jekyll-remote-theme # 使用remote_theme插件实现主题的前后分离，详见<https://github.com/benbalter/jekyll-remote-theme/>

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@5.5.0 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: pretty
timezone: Asia/Hong_Kong # 解决githubpage显示时间不正确的问题，见<https://www.iana.org/time-zones>
future: true # 允许发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: false
      line_numbers: true
    span:
      disable: false

# 以下为 githubpage上不可修改的参数，见<https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
